<a href="https://colab.research.google.com/github/junieberry/ML-PerfectGuide/blob/main/01_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EB%B0%98%EC%9D%98_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B3%BC_%EC%83%9D%ED%83%9C%EA%B3%84_%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 03. 넘파이

In [1]:
import numpy as np

### ndarray
- `np.array` : `ndarray`로 변환 
- `shape` : 차원과 크기를 튜플로 반환
- `ndim` : 차원
---
- `dtype` : 데이터 타입
- `astype` : 데이터 타입 변환
---
- `arrange` : 범위로 생성
- `zeros` : 0으로 생성
- `ones` : 1로 생성
---
- `reshape` : 차원과 크기 변경

In [ ]:
## shape, ndim

array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[2,3,4]])
array3 = np.array([[1,2,3]])

print("array type: ", type(array1))
print("array 1 형태: ", array1.shape)
print("array 2 형태: ", array2.shape)
print("array 3 형태: ", array3.shape)
print("array 1 dim: ", array1.ndim)
print("array 2 dim: ", array2.ndim)
print("array 3 dim: ", array3.ndim)

array type:  <class 'numpy.ndarray'>
array 1 형태:  (3,)
array 2 형태:  (2, 3)
array 3 형태:  (1, 3)
array 1 dim:  1
array 2 dim:  2
array 3 dim:  2


In [ ]:
## dtype, astype

array1 = np.array([1,2,3])
array2 = np.array([1.0,2,3])

print('array1 dtype : ', array1.dtype)
print('array2 dtype : ', array2.dtype)

array_int = np.array([1,2,3])
array_float = array_int.astype('float32')

print('array_int dtype : ', array_int.dtype)
print('array_float dtype : ', array_float.dtype)

array1 dtype :  int64
array2 dtype :  float64
array_int dtype :  int64
array_float dtype :  float32


In [ ]:
## arange, zeros, ones

array_range = np.arange(1,10)
array_zero = np.zeros((2,3))
array_one = np.ones((2,3))

print('array_range : \n', array_range)
print('array_zero : \n', array_zero)
print('array_one : \n', array_one)

array_range : 
 [1 2 3 4 5 6 7 8 9]
array_zero : 
 [[0. 0. 0.]
 [0. 0. 0.]]
array_one : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
## reshape
array1 = np.arange(10)
array2 = array1.reshape(2,5)
array3 = array2.reshape(5,2)

print('array1 :\n', array1)
print('array2 :\n', array2)
print('array3 :\n', array3)
print('-------------------')
array = np.arange(8)
array3d = array.reshape(2,2,2)
array1d = array3d.reshape(-1)
array2d = array1d.reshape(-1,2)


print('array :\n', array1)
print('array3d :\n', array3d)
print('array1d :\n', array1d)
print('array2d :\n', array2d)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
-------------------
array :
 [0 1 2 3 4 5 6 7 8 9]
array3d :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array1d :
 [0 1 2 3 4 5 6 7]
array2d :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


### indexing

- 슬라이싱 : 연속된 인덱스 집합
- 팬시 인덱싱 : 리스트나 ndarray로 인덱싱
- 불린 인덱싱 : 특정 조건에 해당하는 ndarray

In [ ]:
## 슬라이싱
array = np.arange(12)

print(array[1:3])
print(array[:3])
print(array[3:])
print(array[:])
print('---------')

array = array.reshape(3,4)
print(array[:2][1:3])
print(array[1:][1:3])
print(array[:2][1:3])

[1 2]
[0 1 2]
[ 3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
---------
[[4 5 6 7]]
[[ 8  9 10 11]]
[[4 5 6 7]]


In [4]:
## 팬시 인덱싱
array = np.arange(1, 10)
array = array.reshape(3,3)

print(array[[0,1],2])
print(array[[0,1],0:2])
print(array[[0,1]])

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [6]:
## 불린 인덱싱
array = np.arange(10)
print(array[array>5])

[6 7 8 9]


### 정렬
- `np.sort(array)` : 원행렬 유지, 정렬 반환
- `ndarray.sort()` : 원행렬 정렬, 반환 None
- `argsort()`: 정렬된 인덱스 반환

In [11]:
## sort

array = np.array([3,1,9,5])
print('np.sort 반환:', np.sort(array))
print('ndarray.sort 반환', array.sort())

## 내림차순 정렬
## ::-1는 처음부터 끝까지 -1칸 간격으로를 의미한당
print('내림차순', np.sort(array)[::-1])

## axis별 정렬
array = np.array([[8,12], [7,1]])
print('로우 방향으로 정렬\n', np.sort(array, axis = 0))
print('컬럼 방향으로 정렬\n', np.sort(array, axis = 1))

np.sort 반환: [1 3 5 9]
ndarray.sort 반환 None
내림차순 [9 5 3 1]
로우 방향으로 정렬
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬
 [[ 8 12]
 [ 1  7]]


In [12]:
## argsort
array = np.array([3,1,9,5])
print('정렬된 index : ', np.argsort(array))

정렬된 index :  [1 0 3 2]


In [14]:
## argsort 활용

name = np.array(['A','B','C','D'])
score = np.array([78,95,84,88])

sort_index = np.argsort(score)
print('정렬된 이름 : ',name[sort_index])

정렬된 이름 :  ['A' 'C' 'D' 'B']


### 행렬 내적과 전치 행렬
- `np.dot()`
- `np.transpose()`

In [17]:
## 행렬곱

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print('dot product :\n', np.dot(A,B))

dot product :
 [[ 58  64]
 [139 154]]


In [18]:
## 전치행렬

array = np.array([[1,2,3],[4,5,6]])
print('전치행렬 : \n', np.transpose(array))

전치행렬 : 
 [[1 4]
 [2 5]
 [3 6]]


## 04. 판다스

In [19]:
import pandas as pd

### 데이터프레임으로 로딩

- `read_csv` : ,로 구분
- `read_table` : \t으로 구분
- `read_fwf` : 고정 길이 기반

In [49]:
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
titanic_df.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

### 데이터프레임 정보 보기
- `info` : 데이터 건수, 데이터 타입, Null 건수
- `describe` : 숫자형 데이터 값의 분포도, 평균값, 최댓값, 최솟값
- `value_counts` : 해당 칼럼의 유형과 건수

In [26]:
print("type :", type(titanic_df))
print("shape :", titanic_df.shape)
print("info :", titanic_df.info())
print("describe :", titanic_df.describe())

type : <class 'pandas.core.frame.DataFrame'>
shape : (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
info : None
describe :        PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000

In [29]:
print(titanic_df['Pclass'].value_counts())

## Series 객체 (Index + 칼럼)
titanic_pclass = titanic_df['Pclass']
titanic_pclass.head()

3    491
1    216
2    184
Name: Pclass, dtype: int64


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

### 데이터프레임, 리스트, 딕셔너리, ndarray 상호 변환

#### 기타 등등 to DataFrame
- data에 리스트, 딕셔너리나 ndarray
- colunms에 칼럼 명

#### DataFrame to 기타 등등

In [32]:
## data에 리스트나 ndarray
col_name =['one', 'two', 'three']
array = np.array([[1,2,3],[4,5,6]])
df1 = pd.DataFrame(data = array, columns=col_name)

## data에 딕셔너리
dic = { 'one': [1,2], 'two':[3,4]}
df2 = pd.DataFrame(dic)

print(df1)
print(df2)

   one  two  three
0    1    2      3
1    4    5      6
   one  two
0    1    3
1    2    4


In [37]:
## DataFrame to 기타 등등
array = df1.values
print('array :\n', array)

dic = df1.to_dict()
print('dic :', dic)

dic_list = df1.to_dict('list')
print('dic_list :', dic_list)

array :
 [[1 2 3]
 [4 5 6]]
dic : {'one': {0: 1, 1: 4}, 'two': {0: 2, 1: 5}, 'three': {0: 3, 1: 6}}
dic_list : {'one': [1, 4], 'two': [2, 5], 'three': [3, 6]}


### 데이터프레임 CRUD

데이터 삭제 `drop`
- `axis` : 0이면 행, 1이면 열
- `label`: 행이면 index, 열이면 column 이름

In [41]:
## 기존 칼럼 실수로 일괄 업데이트
titanic_df['Age'] = 0

## 기존 칼럼 기반 새로운 칼럼
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1

## 데이터 삭제 (inplace == True라면 원본도 함께 삭제된다)
titanic_drop = titanic_df.drop('Age', axis = 1, inplace=True)

titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   

             Ticket     Fare Cabin Embarked  Family_No  
0         A/5 21171   7.2500   NaN        S          2  
1          PC 17599  71.2833   C85        C          2  
2  STON/O2. 3101282   7.9250   NaN        S          1

### 인덱스

- 고유의 값으로, 불변
- 연산을 수행해도 인덱스는 변하지 않음
- `reset_index` 시 기존 index는 새 column으로 들어가고 새 index 생성

In [42]:
## reset_index

value_count = titanic_df['Pclass'].value_counts()
print(value_count)
value_count = value_count.reset_index()
print(value_count)

3    491
1    216
2    184
Name: Pclass, dtype: int64
   index  Pclass
0      3     491
1      1     216
2      2     184


### 데이터 셀렉션 및 필터링 및 인덱싱

**DataFrame의 [] 연산자**
- 칼럼 이름 혹은 인덱스로 변환 가능한 표현식
- 칼럼명, 칼럼 리스트, 불린 인덱스로만 사용하자

<br>

**명칭 기반 인덱싱** : 칼럼 명칭 기반

**위치 기반 인덱싱** : 0부터 행, 열 위치

<br>


**ix[ ] 연산자**
- 명칭 기반 인덱싱과 위치 기반 인덱싱을 모두 허용
- deprecated

**iloc[ ] 연산자**
- 위치 기반 인덱싱만 허용

**loc[ ] 연산자**
- 명칭 기반으로 추출
- 슬라이싱할때 종료값까지 포함 (명칭 -1 불가능)

In [47]:
## 불린 인덱싱
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
print(titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3))

cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'

print(titanic_df[cond1&cond2&cond3])

                              Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0
     PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN  


### 정렬, Aggregation, GroupBy

**sort_values()**
- by (특정 칼럼으로 정렬)
- ascending (true면 오름차순)
- inplace (false면 기존 데이터셋 유지)

**Aggregation**
- `min()`
- `max()`
- `sum()`
- `count()`

**GroupBy**
- by에 칼럼 입력 시 대상 칼럼으로 groupby
- groupby 호출해 반환된 결과에 aggregation 적용하면 groupby() 칼럼 제외한 칼럼에 적용

In [50]:
## sort

titanic_sort = titanic_df.sort_values(by=['Name','Pclass'], ascending=False)
titanic_sort.head(3)

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
361          362         0       2        del Carlo, Mr. Sebastiano  male   

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
868   NaN      0      0         345777   9.5000   NaN        S  
153  40.5      0      2       A/5. 851  14.5000   NaN        S  
361  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C

In [51]:
## agregation

titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

### 결손 데이터 처리하기

- 결손 데이터 = Null 값
- `isna()` : NaN 값 구분
- `fillna()` : NaN 다른 값으로 대체

In [54]:
## isna()

## 결손 데이터 수
print(titanic_df.isna())
titanic_df.isna().sum()

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [55]:
## fillna

titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
# or
titanic_df['Cabin'].fillna('C000', inplace=True)


### apply lambda 식으로 데이터 가공

In [ ]:
## lambda

square = lambda x : x**2

In [57]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [58]:
titanic_df['Child'] = titanic_df['Age'].apply(lambda x: True if x<=15 else False)
titanic_df[['Age', 'Child']].head(8)

Age  Child
0  22.0  False
1  38.0  False
2  26.0  False
3  35.0  False
4  35.0  False
5   NaN  False
6  54.0  False
7   2.0   True